/*
 * init.sql
 *
 * Initialization script executes on FBSQL start up,
 * connects to database instance and optionally performs
 * any operations that you want to be executed at start up time
 */

CONNECT TO 'jdbc:sqlite:sample';

DROP TABLE IF EXISTS COUNTRIES;
CREATE TABLE IF NOT EXISTS COUNTRIES (
    COUNTRY_ID   CHAR(2)     NOT NULL PRIMARY KEY,
    COUNTRY_NAME VARCHAR(40) NOT NULL,
    COUNTRY_FLAG BLOB
);

INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, COUNTRY_FLAG) VALUES('AU', 'Australia', 'data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==');
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, COUNTRY_FLAG) VALUES('DE', 'Germany',   'data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==');
INSERT INTO COUNTRIES (COUNTRY_ID, COUNTRY_NAME, COUNTRY_FLAG) VALUES('IN', 'India',     'data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==');
